# Extends the configuration for development (inits and mounting directory into core)
services:
  postgresinit:
    image: postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src
    container_name: odota-postgresinit
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 15 && psql --file /usr/src/sql/init.sql postgres://postgres:postgres@odota-postgres/postgres && psql --file /usr/src/sql/create_tables.sql postgres://postgres:postgres@odota-postgres/yasp',
      ]
  cassandrainit:
    image: cassandra
    depends_on:
      cassandra:
        condition: service_started
    volumes:
      - .:/usr/src
    container_name: odota-cassandrainit
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 60 && cqlsh -f /usr/src/sql/init.cql odota-cassandra && cqlsh -f /usr/src/sql/create_tables.cql -k yasp odota-cassandra',
      ]
  minioinit:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started
    volumes:
      - .:/usr/src
    container_name: odota-minioinit
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://odota-minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/opendota-blobs;
      /usr/bin/mc mb myminio/opendota;
      /usr/bin/mc mb myminio/opendota-players;
      exit 0;
      "
  core:
    entrypoint: bash launch.sh
    volumes:
      - .:/usr/src
