# Extends the configuration for development (inits and mounting directory into core)
version: '3'
services:
  postgresinit:
    image: postgres
    depends_on:
      - postgres
    volumes:
      - .:/usr/src
    container_name: odota-postgresinit
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 10 && psql --file /usr/src/sql/init.sql postgres://postgres:postgres@odota-postgres/postgres && psql --file /usr/src/sql/create_tables.sql postgres://postgres:postgres@odota-postgres/yasp',
      ]
  cassandrainit:
    image: cassandra
    depends_on:
      - cassandra
    volumes:
      - .:/usr/src
    container_name: odota-cassandrainit
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 45 && cqlsh -f /usr/src/sql/init.cql odota-cassandra && cqlsh -f /usr/src/sql/create_tables.cql -k yasp odota-cassandra',
      ]
  minioinit:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - .:/usr/src
    container_name: odota-minioinit
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc mb opendota-blobs;
      /usr/bin/mc mb opendota;
      /usr/bin/mc mb opendota-players;
      exit 0;
      "
  core:
    entrypoint: bash scripts/launch.sh
    volumes:
      - .:/usr/src
