services:
  postgres:
    image: postgres:9.5
    container_name: odota-postgres
    environment:
      POSTGRES_PASSWORD: postgres
  cassandra:
    image: cassandra:5.0
    container_name: odota-cassandra
    environment:
      JVM_EXTRA_OPTS: -Dcassandra.skip_wait_for_gossip_to_settle=0
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: odota-minio
    command: server /data
  redis:
    image: redis:7
    container_name: odota-redis
  elasticsearch:
    image: elasticsearch:7.17.0
    platform: linux/arm64
    container_name: odota-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  parser:
    image: odota/parser
    container_name: odota-parser
  core:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sleep infinity
    ports:
      - '5000:5000'
      - '5100:5100'
    environment:
      PARSER_HOST: odota-parser:5600
      POSTGRES_URL: postgresql://postgres:postgres@odota-postgres/yasp
      READONLY_POSTGRES_URL: postgresql://readonly:readonly@odota-postgres/yasp
      REDIS_URL: redis://odota-redis:6379/0
      CASSANDRA_URL: cassandra://odota-cassandra/yasp
      ELASTICSEARCH_URL: odota-elasticsearch:9200
      ARCHIVE_S3_ENDPOINT: http://odota-minio:9000
    links:
      - postgres
      - redis
      - elasticsearch
      - parser
      - minio
      - cassandra
    container_name: odota-core
